import { getRandomWordByDifficulty, getWordCount, insertWords } from "../../../storage/sqlite";

interface SeedWord {
	word: string;
	difficulty: number; // 1=easy, 2=medium, 3=hard, 4=super hard (reserved)
}

const SEED_WORDS_RU: SeedWord[] = [
	// ========================================
	// Difficulty 1 (easy) — бытовые предметы, еда, животные, части тела
	// ========================================
	{ word: "кошка", difficulty: 1 },
	{ word: "собака", difficulty: 1 },
	{ word: "дерево", difficulty: 1 },
	{ word: "солнце", difficulty: 1 },
	{ word: "луна", difficulty: 1 },
	{ word: "дом", difficulty: 1 },
	{ word: "река", difficulty: 1 },
	{ word: "дождь", difficulty: 1 },
	{ word: "снег", difficulty: 1 },
	{ word: "огонь", difficulty: 1 },
	{ word: "вода", difficulty: 1 },
	{ word: "книга", difficulty: 1 },
	{ word: "яблоко", difficulty: 1 },
	{ word: "банан", difficulty: 1 },
	{ word: "молоко", difficulty: 1 },
	{ word: "чай", difficulty: 1 },
	{ word: "кофе", difficulty: 1 },
	{ word: "хлеб", difficulty: 1 },
	{ word: "мяч", difficulty: 1 },
	{ word: "стол", difficulty: 1 },
	{ word: "стул", difficulty: 1 },
	{ word: "окно", difficulty: 1 },
	{ word: "дверь", difficulty: 1 },
	{ word: "ключ", difficulty: 1 },
	{ word: "часы", difficulty: 1 },
	{ word: "телефон", difficulty: 1 },
	{ word: "машина", difficulty: 1 },
	{ word: "поезд", difficulty: 1 },
	{ word: "медведь", difficulty: 1 },
	{ word: "рыба", difficulty: 1 },
	{ word: "птица", difficulty: 1 },
	{ word: "цветок", difficulty: 1 },
	{ word: "звезда", difficulty: 1 },
	{ word: "облако", difficulty: 1 },
	{ word: "земля", difficulty: 1 },
	{ word: "автобус", difficulty: 1 },
	{ word: "бабушка", difficulty: 1 },
	{ word: "борщ", difficulty: 1 },
	{ word: "ботинок", difficulty: 1 },
	{ word: "брат", difficulty: 1 },
	{ word: "варежки", difficulty: 1 },
	{ word: "варенье", difficulty: 1 },
	{ word: "волк", difficulty: 1 },
	{ word: "герой", difficulty: 1 },
	{ word: "голова", difficulty: 1 },
	{ word: "дедушка", difficulty: 1 },
	{ word: "диван", difficulty: 1 },
	{ word: "живот", difficulty: 1 },
	{ word: "жук", difficulty: 1 },
	{ word: "заяц", difficulty: 1 },
	{ word: "зебра", difficulty: 1 },
	{ word: "зонт", difficulty: 1 },
	{ word: "зуб", difficulty: 1 },
	{ word: "игрушка", difficulty: 1 },
	{ word: "карандаш", difficulty: 1 },
	{ word: "конфета", difficulty: 1 },
	{ word: "костюм", difficulty: 1 },
	{ word: "котлета", difficulty: 1 },
	{ word: "кровать", difficulty: 1 },
	{ word: "кукла", difficulty: 1 },
	{ word: "курица", difficulty: 1 },
	{ word: "лампа", difficulty: 1 },
	{ word: "лев", difficulty: 1 },
	{ word: "лиса", difficulty: 1 },
	{ word: "лягушка", difficulty: 1 },
	{ word: "мама", difficulty: 1 },
	{ word: "мышка", difficulty: 1 },
	{ word: "небо", difficulty: 1 },
	{ word: "нога", difficulty: 1 },
	{ word: "ножницы", difficulty: 1 },
	{ word: "нос", difficulty: 1 },
	{ word: "пальто", difficulty: 1 },
	{ word: "панда", difficulty: 1 },
	{ word: "папа", difficulty: 1 },
	{ word: "пицца", difficulty: 1 },
	{ word: "подарок", difficulty: 1 },
	{ word: "портфель", difficulty: 1 },
	{ word: "праздник", difficulty: 1 },
	{ word: "пчела", difficulty: 1 },
	{ word: "рука", difficulty: 1 },
	{ word: "ручка", difficulty: 1 },
	{ word: "санки", difficulty: 1 },
	{ word: "сестра", difficulty: 1 },
	{ word: "суп", difficulty: 1 },
	{ word: "сыр", difficulty: 1 },
	{ word: "тетрадь", difficulty: 1 },
	{ word: "тигр", difficulty: 1 },
	{ word: "трава", difficulty: 1 },
	{ word: "троллейбус", difficulty: 1 },
	{ word: "ухо", difficulty: 1 },
	{ word: "учитель", difficulty: 1 },
	{ word: "хвост", difficulty: 1 },
	{ word: "чайник", difficulty: 1 },
	{ word: "шапка", difficulty: 1 },
	{ word: "шарик", difficulty: 1 },
	{ word: "шарф", difficulty: 1 },
	{ word: "школа", difficulty: 1 },
	{ word: "язык", difficulty: 1 },
	{ word: "ёлка", difficulty: 1 },

	// ========================================
	// Difficulty 2 (medium) — менее очевидные, техника, профессии, спорт
	// ========================================
	{ word: "океан", difficulty: 2 },
	{ word: "гора", difficulty: 2 },
	{ word: "мост", difficulty: 2 },
	{ word: "дорога", difficulty: 2 },
	{ word: "город", difficulty: 2 },
	{ word: "самолёт", difficulty: 2 },
	{ word: "корабль", difficulty: 2 },
	{ word: "велосипед", difficulty: 2 },
	{ word: "музыка", difficulty: 2 },
	{ word: "фильм", difficulty: 2 },
	{ word: "театр", difficulty: 2 },
	{ word: "картина", difficulty: 2 },
	{ word: "танец", difficulty: 2 },
	{ word: "песня", difficulty: 2 },
	{ word: "апельсин", difficulty: 2 },
	{ word: "арбуз", difficulty: 2 },
	{ word: "виноград", difficulty: 2 },
	{ word: "клубника", difficulty: 2 },
	{ word: "вишня", difficulty: 2 },
	{ word: "лимон", difficulty: 2 },
	{ word: "шоколад", difficulty: 2 },
	{ word: "мороженое", difficulty: 2 },
	{ word: "пирог", difficulty: 2 },
	{ word: "печенье", difficulty: 2 },
	{ word: "сок", difficulty: 2 },
	{ word: "слон", difficulty: 2 },
	{ word: "жираф", difficulty: 2 },
	{ word: "дельфин", difficulty: 2 },
	{ word: "пингвин", difficulty: 2 },
	{ word: "бабочка", difficulty: 2 },
	{ word: "орёл", difficulty: 2 },
	{ word: "футбол", difficulty: 2 },
	{ word: "баскетбол", difficulty: 2 },
	{ word: "теннис", difficulty: 2 },
	{ word: "плавание", difficulty: 2 },
	{ word: "бег", difficulty: 2 },
	{ word: "зеркало", difficulty: 2 },
	{ word: "замок", difficulty: 2 },
	{ word: "свеча", difficulty: 2 },
	{ word: "зонтик", difficulty: 2 },
	{ word: "рюкзак", difficulty: 2 },
	{ word: "радуга", difficulty: 2 },
	{ word: "водопад", difficulty: 2 },
	{ word: "остров", difficulty: 2 },
	{ word: "авария", difficulty: 2 },
	{ word: "актёр", difficulty: 2 },
	{ word: "акула", difficulty: 2 },
	{ word: "аплодисменты", difficulty: 2 },
	{ word: "аптека", difficulty: 2 },
	{ word: "балкон", difficulty: 2 },
	{ word: "батарейка", difficulty: 2 },
	{ word: "библиотека", difficulty: 2 },
	{ word: "билет", difficulty: 2 },
	{ word: "бинокль", difficulty: 2 },
	{ word: "биология", difficulty: 2 },
	{ word: "больница", difficulty: 2 },
	{ word: "водитель", difficulty: 2 },
	{ word: "газета", difficulty: 2 },
	{ word: "гимнаст", difficulty: 2 },
	{ word: "голос", difficulty: 2 },
	{ word: "градусник", difficulty: 2 },
	{ word: "директор", difficulty: 2 },
	{ word: "журнал", difficulty: 2 },
	{ word: "забор", difficulty: 2 },
	{ word: "задание", difficulty: 2 },
	{ word: "зарядка", difficulty: 2 },
	{ word: "звонок", difficulty: 2 },
	{ word: "зоопарк", difficulty: 2 },
	{ word: "игра", difficulty: 2 },
	{ word: "каникулы", difficulty: 2 },
	{ word: "карта", difficulty: 2 },
	{ word: "кастрюля", difficulty: 2 },
	{ word: "кирпич", difficulty: 2 },
	{ word: "клад", difficulty: 2 },
	{ word: "комната", difficulty: 2 },
	{ word: "компас", difficulty: 2 },
	{ word: "контрольная", difficulty: 2 },
	{ word: "концерт", difficulty: 2 },
	{ word: "костёр", difficulty: 2 },
	{ word: "кубок", difficulty: 2 },
	{ word: "кулисы", difficulty: 2 },
	{ word: "линейка", difficulty: 2 },
	{ word: "лифт", difficulty: 2 },
	{ word: "маркер", difficulty: 2 },
	{ word: "медаль", difficulty: 2 },
	{ word: "микрофон", difficulty: 2 },
	{ word: "музей", difficulty: 2 },
	{ word: "наушники", difficulty: 2 },
	{ word: "новость", difficulty: 2 },
	{ word: "обои", difficulty: 2 },
	{ word: "оркестр", difficulty: 2 },
	{ word: "палатка", difficulty: 2 },
	{ word: "парикмахер", difficulty: 2 },
	{ word: "паспорт", difficulty: 2 },
	{ word: "перемена", difficulty: 2 },
	{ word: "пешеход", difficulty: 2 },
	{ word: "пилот", difficulty: 2 },
	{ word: "планшет", difficulty: 2 },
	{ word: "плита", difficulty: 2 },
	{ word: "победа", difficulty: 2 },
	{ word: "потолок", difficulty: 2 },
	{ word: "принцесса", difficulty: 2 },
	{ word: "профессия", difficulty: 2 },
	{ word: "путешествие", difficulty: 2 },
	{ word: "пылесос", difficulty: 2 },
	{ word: "радио", difficulty: 2 },
	{ word: "светофор", difficulty: 2 },
	{ word: "сериал", difficulty: 2 },
	{ word: "скейтборд", difficulty: 2 },
	{ word: "сковорода", difficulty: 2 },
	{ word: "собрание", difficulty: 2 },
	{ word: "сосед", difficulty: 2 },
	{ word: "спектакль", difficulty: 2 },
	{ word: "спортсмен", difficulty: 2 },
	{ word: "стройка", difficulty: 2 },
	{ word: "сцена", difficulty: 2 },
	{ word: "танцор", difficulty: 2 },
	{ word: "телевизор", difficulty: 2 },
	{ word: "теннисист", difficulty: 2 },
	{ word: "термометр", difficulty: 2 },
	{ word: "тренер", difficulty: 2 },
	{ word: "урок", difficulty: 2 },
	{ word: "физика", difficulty: 2 },
	{ word: "фонарик", difficulty: 2 },
	{ word: "футболист", difficulty: 2 },
	{ word: "химия", difficulty: 2 },
	{ word: "холодильник", difficulty: 2 },
	{ word: "цемент", difficulty: 2 },
	{ word: "шахматист", difficulty: 2 },
	{ word: "экзамен", difficulty: 2 },
	{ word: "экскурсия", difficulty: 2 },

	// ========================================
	// Difficulty 3 (hard) — абстрактные, научные, редкие
	// ========================================
	{ word: "ветер", difficulty: 3 },
	{ word: "скульптура", difficulty: 3 },
	{ word: "крокодил", difficulty: 3 },
	{ word: "шахматы", difficulty: 3 },
	{ word: "лыжи", difficulty: 3 },
	{ word: "гимнастика", difficulty: 3 },
	{ word: "фонарь", difficulty: 3 },
	{ word: "молния", difficulty: 3 },
	{ word: "вулкан", difficulty: 3 },
	{ word: "пустыня", difficulty: 3 },
	{ word: "джунгли", difficulty: 3 },
	{ word: "пещера", difficulty: 3 },
	{ word: "робот", difficulty: 3 },
	{ word: "ракета", difficulty: 3 },
	{ word: "компьютер", difficulty: 3 },
	{ word: "камера", difficulty: 3 },
	{ word: "телескоп", difficulty: 3 },
	{ word: "микроскоп", difficulty: 3 },
	{ word: "спутник", difficulty: 3 },
	{ word: "клоун", difficulty: 3 },
	{ word: "пират", difficulty: 3 },
	{ word: "рыцарь", difficulty: 3 },
	{ word: "космонавт", difficulty: 3 },
	{ word: "повар", difficulty: 3 },
	{ word: "художник", difficulty: 3 },
	{ word: "детектив", difficulty: 3 },
	{ word: "волшебник", difficulty: 3 },
	{ word: "подушка", difficulty: 3 },
	{ word: "лестница", difficulty: 3 },
	{ word: "качели", difficulty: 3 },
	{ word: "карусель", difficulty: 3 },
	{ word: "фонтан", difficulty: 3 },
	{ word: "маяк", difficulty: 3 },
	{ word: "воздушный шар", difficulty: 3 },
	{ word: "парашют", difficulty: 3 },
	{ word: "абонемент", difficulty: 3 },
	{ word: "абстракция", difficulty: 3 },
	{ word: "абсурд", difficulty: 3 },
	{ word: "авангард", difficulty: 3 },
	{ word: "агорафобия", difficulty: 3 },
	{ word: "алгоритм", difficulty: 3 },
	{ word: "анализ", difficulty: 3 },
	{ word: "аналогия", difficulty: 3 },
	{ word: "анархия", difficulty: 3 },
	{ word: "антагонизм", difficulty: 3 },
	{ word: "антагонист", difficulty: 3 },
	{ word: "антиутопия", difficulty: 3 },
	{ word: "аргумент", difficulty: 3 },
	{ word: "барокко", difficulty: 3 },
	{ word: "бюрократия", difficulty: 3 },
	{ word: "гипербола", difficulty: 3 },
	{ word: "гипотеза", difficulty: 3 },
	{ word: "глобализация", difficulty: 3 },
	{ word: "гравитация", difficulty: 3 },
	{ word: "демократия", difficulty: 3 },
	{ word: "деформация", difficulty: 3 },
	{ word: "диагностика", difficulty: 3 },
	{ word: "дилемма", difficulty: 3 },
	{ word: "дискуссия", difficulty: 3 },
	{ word: "идеология", difficulty: 3 },
	{ word: "иллюзия", difficulty: 3 },
	{ word: "иммунитет", difficulty: 3 },
	{ word: "импровизация", difficulty: 3 },
	{ word: "интуиция", difficulty: 3 },
	{ word: "инфляция", difficulty: 3 },
	{ word: "ирония", difficulty: 3 },
	{ word: "катарсис", difficulty: 3 },
	{ word: "катастрофа", difficulty: 3 },
	{ word: "квант", difficulty: 3 },
	{ word: "клаустрофобия", difficulty: 3 },
	{ word: "колонизация", difficulty: 3 },
	{ word: "компиляция", difficulty: 3 },
	{ word: "конспирация", difficulty: 3 },
	{ word: "концепция", difficulty: 3 },
	{ word: "критика", difficulty: 3 },
	{ word: "лаборант", difficulty: 3 },
	{ word: "манифест", difficulty: 3 },
	{ word: "медитация", difficulty: 3 },
	{ word: "менталитет", difficulty: 3 },
	{ word: "метаморфоза", difficulty: 3 },
	{ word: "метафора", difficulty: 3 },
	{ word: "минимализм", difficulty: 3 },
	{ word: "модерн", difficulty: 3 },
	{ word: "монархия", difficulty: 3 },
	{ word: "мутация", difficulty: 3 },
	{ word: "нейрон", difficulty: 3 },
	{ word: "нирвана", difficulty: 3 },
	{ word: "оптимизация", difficulty: 3 },
	{ word: "пандемия", difficulty: 3 },
	{ word: "парадокс", difficulty: 3 },
	{ word: "празднование", difficulty: 3 },
	{ word: "прогресс", difficulty: 3 },
	{ word: "протагонист", difficulty: 3 },
	{ word: "психология", difficulty: 3 },
	{ word: "революция", difficulty: 3 },
	{ word: "регресс", difficulty: 3 },
	{ word: "рекурсия", difficulty: 3 },
	{ word: "ренессанс", difficulty: 3 },
	{ word: "рефлексия", difficulty: 3 },
	{ word: "сарказм", difficulty: 3 },
	{ word: "сатира", difficulty: 3 },
	{ word: "симуляция", difficulty: 3 },
	{ word: "синтез", difficulty: 3 },
	{ word: "телепатия", difficulty: 3 },
	{ word: "теория", difficulty: 3 },
	{ word: "урбанизация", difficulty: 3 },
	{ word: "утопия", difficulty: 3 },
	{ word: "философия", difficulty: 3 },
	{ word: "эволюция", difficulty: 3 },
	{ word: "экспрессионизм", difficulty: 3 },
	{ word: "эмпатия", difficulty: 3 },
	{ word: "эпидемия", difficulty: 3 },
	{ word: "эстетика", difficulty: 3 },
	{ word: "этика", difficulty: 3 },

	// ========================================
	// Difficulty 4 (super hard) — узкоспециальные, философские (резерв, не используется в UI)
	// ========================================
	{ word: "аллюзия", difficulty: 4 },
	{ word: "амбивалентность", difficulty: 4 },
	{ word: "аутентификация", difficulty: 4 },
	{ word: "декаданс", difficulty: 4 },
	{ word: "дефляция", difficulty: 4 },
	{ word: "когнитивность", difficulty: 4 },
	{ word: "конформизм", difficulty: 4 },
	{ word: "легитимность", difficulty: 4 },
	{ word: "нонконформизм", difficulty: 4 },
	{ word: "объективность", difficulty: 4 },
	{ word: "оксюморон", difficulty: 4 },
	{ word: "реминисценция", difficulty: 4 },
	{ word: "репрезентация", difficulty: 4 },
	{ word: "субординация", difficulty: 4 },
	{ word: "субъективность", difficulty: 4 },
	{ word: "трансцендентность", difficulty: 4 },
	{ word: "утончённость", difficulty: 4 },
	{ word: "химеричность", difficulty: 4 },
	{ word: "эвфемизм", difficulty: 4 },
	{ word: "экзистенция", difficulty: 4 },
];

export function seedWords(): void {
	const before = getWordCount("ru");
	insertWords(
		SEED_WORDS_RU.map((w) => ({
			word: w.word,
			language: "ru",
			difficulty: w.difficulty,
		})),
	);
	const after = getWordCount("ru");
	const added = after - before;
	if (added > 0) {
		console.log(`[words] seeded ${added} new Russian words (total: ${after})`);
	}
}

export function getWord(language: string = "ru", difficulty: number | null = null): string {
	const word = getRandomWordByDifficulty(language, difficulty);
	if (word) {
		return word;
	}

	// Fallback to hardcoded list (filtered by difficulty if specified)
	const pool =
		difficulty === null ? SEED_WORDS_RU : SEED_WORDS_RU.filter((w) => w.difficulty === difficulty);
	const list = pool.length > 0 ? pool : SEED_WORDS_RU;
	return list[Math.floor(Math.random() * list.length)]!.word;
}
